#!/bin/bash
# version 0.2.0
set -e

DIR="$1"
SYNCER_URL="$2"
SYNCER_TOKEN="$3"

if [[ -z "$DIR" ]] || [[ -z "$SYNCER_URL" ]] || [[ -z "$SYNCER_TOKEN" ]]; then
  echo 'Usage sync-files DIR SYNCER_URL SYNCER_TOKEN'
  exit
fi

cd "$DIR" || exit

echo 'Start syncing files...'

echo "Fetching remote file modification times..."
remoteFiles=$(curl --fail -sS -H "Auth-Token: $SYNCER_TOKEN" "$SYNCER_URL?action=files" | jq)

if [ "$remoteFiles" == "" ]
then
  echo "Error: fetching remote file modification times failed!"
  exit 1
fi

postParams=""
i=0
while read -rd $'\0' file; do
  modifiedTime=$(date -r "$file" "+%s")
  remoteModifiedTime=$(echo "$remoteFiles" | jq -r '."'"$file"'"')

  if [ "$remoteModifiedTime" == null ] || [ "$modifiedTime" -gt "$remoteModifiedTime" ]
  then
    postParams+=" -F files[]=@$file"
    postParams+=" -F filePaths[]=$file"

    i=$((i+1))
  fi
  postParams+=" -F fileList[]=$file"
done < <(find * -type f -print0)

echo "Uploading files: $i"

syncedFiles=$(curl -sS -H "Auth-Token: $SYNCER_TOKEN" $postParams "$SYNCER_URL")
if [ "$syncedFiles" != "" ]
then
  echo "$syncedFiles" | jq
else
  echo "Error: uploading files failed!"
  exit 1
fi
